import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {MISSIONS,type Mission} from '@/lib/missions';
import {AtelierQualite} from './qualite';
import {PlanContinuite} from './continuite';
import {Commandes} from './commandes';
export const metadata={title:'Vos équipes au travail — Gerimmo'};
const noms:Record<string,string>={reussi:'Passage terminé',a_reprendre:'À vérifier',interrompu:'Passage interrompu',en_cours:'En cours'};
export default async function Page(){
 const db=await createClient();const [regles,historique]=await Promise.all([db.from('agent_missions').select('cle,active'),db.from('agent_passages').select('id,mission,debut,fin,expiration,etat,resume,compte').order('debut',{ascending:false}).limit(200)]);
 const {data:plan,error:erreurPlan}=await db.rpc('etat_continuite');
 const disponible=!regles.error&&!historique.error;
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-7"><header className="rounded-2xl bg-gradient-to-r from-[var(--encre)] to-[var(--marque)] p-6 text-white"><p className="text-xs uppercase tracking-widest">Centre de commandement</p><h1 style={{color:'white'}} className="mt-2 text-3xl font-semibold">Vos équipes au travail</h1><p className="mt-3 max-w-3xl">Retrouvez les passages réellement effectués, leurs résultats et les prochaines heures de travail. Les réglages de chaque agence, les validations et les plafonds de dépenses restent applicables.</p></header><nav className="flex flex-wrap gap-3"><Link className="btn-secondaire" href="/admin/autonomie">Dossiers et décisions</Link><Link className="btn-secondaire" href="/admin/sante">Connexions et difficultés</Link><Link className="btn-secondaire" href="/admin/autonomie#ameliorations">Équipe qualité et corrections</Link></nav>
 {!disponible&&<p role="alert" className="err">Le suivi est indisponible. Aucun état « à jour » ne peut être confirmé.</p>}
 <div className="grid gap-4 lg:grid-cols-2">{Object.entries(MISSIONS).map(([cle,m])=>{const regle=regles.data?.find(r=>r.cle===cle);const passages=historique.data?.filter(p=>p.mission===cle)??[];const dernier=passages[0];const retard=dernier&&new Date().getTime()-new Date(dernier.debut).getTime()>36*3600000;const expire=dernier?.etat==='en_cours'&&new Date(dernier.expiration)<new Date();return <section key={cle} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs text-muted-foreground">Équipe {m.equipe}</p><h2 className="mt-1 text-xl font-semibold">{m.nom}</h2><p className="mt-2 font-medium">{!disponible||!regle?'État indisponible':!regle.active?'En pause':expire?'Passage à vérifier':retard?'Aucun passage depuis plus de 36 heures':dernier?noms[dernier.etat]:'Premier passage attendu'}</p><p className="mt-1 text-sm text-muted-foreground">Passage quotidien : {m.heure}. Le traitement peut ne rien avoir à faire si aucune action n’est due.</p>{disponible&&regle&&<Commandes mission={cle as Mission} active={regle.active}/>}<Link className="mt-3 inline-block text-sm underline" href={m.lien}>Ouvrir les dossiers concernés</Link><details className="mt-4 border-t pt-3"><summary className="cursor-pointer font-medium">Derniers passages</summary><ol className="mt-3 space-y-3">{passages.slice(0,8).map(p=><li key={p.id} className="rounded-xl bg-muted/40 p-3 text-sm"><b>{new Date(p.debut).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</b><p>{noms[p.etat]} · {p.compte} résultat(s) comptabilisé(s)</p><p>{p.resume??'Le résultat sera enregistré à la fin du passage.'}</p></li>)}{!passages.length&&<li className="text-sm">Aucun passage enregistré depuis la mise en place de ce suivi.</li>}</ol></details></section>})}</div><AtelierQualite connecte={Boolean(process.env.GITHUB_AGENT_TOKEN)&&process.env.GERIMMO_CODEX_ENABLED==='true'}/><section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-semibold">Continuer en votre absence</h2>{erreurPlan||!plan?<p className="err">Le plan de continuité est indisponible.</p>:<><p className="mt-2">{!plan.derniere_presence?'Dernière présence inconnue.':plan.absence?'Le délai d’absence prévu est dépassé.':'Une présence de supervision a été enregistrée récemment.'} {plan.responsable_habilite?'Le responsable désigné possède déjà les droits nécessaires.':'Aucun responsable de remplacement habilité n’est confirmé.'}</p><PlanContinuite jours={plan.delai_jours} email={plan.responsable??''} consignes={plan.consignes??''}/></>}</section><p className="text-sm text-muted-foreground">L’équipe qualité suit les propositions et leurs contrôles dans « Dossiers et décisions ». Une proposition n’est pas une correction déjà publiée.</p></main>;
}
