import { createClient } from '@/lib/supabase/server';
type Ligne={automatiques:number;humaines:number};
type Mesures=Ligne&{messages:number;sans_appel:number;avec_appel:number;clics_minimum:number;organisations:(Ligne&{organization_id:string|null;nom:string|null;messages:number})[];domaines:(Ligne&{domaine:string})[]};
const domaines:Record<string,string>={location:'Locations et états des lieux',incident:'Incidents et artisans',finance:'Finances',document:'Documents et signatures',message:'Messages',marketing:'Marketing',territoire:'Développement territorial',qualite:'Qualité'};
function taux(m:Ligne){const total=Number(m.automatiques)+Number(m.humaines);return total?`${Math.round(100*Number(m.automatiques)/total)} %`:'En attente';}
export async function MesureAutonomie({orgId,detail=false}:{orgId?:string;detail?:boolean}) {
 const db=await createClient();const {data,error}=await db.rpc('mesures_automatisation',{p_org:orgId??null});const m=error?null:data as Mesures|null;
 return <section className="section-ecran space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">30 derniers jours · objectif : 90 %</p><h2 className="text-xl font-semibold text-[var(--encre)]">Ce que Gerimmo fait pour vous</h2></div><span className="puce puce-prep">{m&&Number(m.automatiques)+Number(m.humaines)>0?`${taux(m)} des actions suivies`:'Mesure en démarrage'}</span></div>
  {!m&&<p role="alert" className="err">Les mesures sont momentanément indisponibles. Les chiffres manquants ne sont pas des zéros.</p>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['Actions automatiques',m?.automatiques],['Actions humaines',m?.humaines],['Messages déposés ou transmis',m?.messages],['Dossiers confirmés sans appel',m?.sans_appel],['Dossiers confirmés avec appel',m?.avec_appel],['Clics d’envoi évités au minimum',m?.clics_minimum]].map(([nom,v])=><div key={String(nom)} className="kpi bleu"><span className="libelle-champ">{nom}</span><strong className="chiffre block">{v??'—'}</strong></div>)}</div>
  <details className="rounded-xl border border-border bg-white p-4"><summary className="cursor-pointer font-semibold">Comprendre ces chiffres</summary><div className="mt-3 space-y-2 text-sm text-muted-foreground"><p>Le taux compare les résultats enregistrés automatiquement aux résultats enregistrés par une personne. Il mesure des actions, pas du temps de travail. Un lot de documents peut produire plusieurs résultats.</p><p>Les clics comparent les quittances automatiques au bouton d’envoi groupé du mois : un seul clic minimum par organisation et mois terminé, uniquement si toutes les quittances ont une trace d’envoi automatique dans les 30 derniers jours. Les mois avec un envoi manuel, un document non envoyé ou une trace manquante sont exclus. Navigation et saisie ne sont pas comptées.</p><p>Le bilan avec ou sans appel est une confirmation du gestionnaire enregistrée pendant cette période. Les dossiers sans confirmation ne sont classés dans aucune des deux catégories. Un message accepté par le service n’est pas une preuve de lecture.</p><p>La mesure couvre les étapes des baux et incidents, les encaissements, les quittances et avis transmis, les rappels, les documents classés, retours signés, devis et avenants, comptes rendus d’intervention, états des lieux signés et messages du site. Elle ne couvre pas encore les appels téléphoniques eux-mêmes, le travail hors plateforme, ni tous les gestes administratifs. Le taux de 90 % sur toute la gestion n’est donc pas encore démontré.</p></div></details>
  {m&&<details className="rounded-xl border border-border bg-white p-4"><summary className="cursor-pointer font-semibold">Résultats par activité</summary><div className="mt-3 grid gap-3 sm:grid-cols-2">{m.domaines.map(d=><div key={d.domaine} className="rounded-lg bg-muted/40 p-3"><b className="text-sm">{domaines[d.domaine]??'Autres actions suivies'}</b><p className="mt-1 text-sm">{d.automatiques} automatiques · {d.humaines} humaines · {taux(d)}</p></div>)}{m.domaines.length===0&&<p className="text-sm">Aucune action mesurée pendant cette période.</p>}</div></details>}
  {detail&&m&&<div className="overflow-x-auto" tabIndex={0} role="region" aria-label="Automatisation par organisation"><table className="tableau w-full text-sm"><thead><tr><th className="text-left">Organisation</th><th>Automatiques</th><th>Humaines</th><th>Messages</th><th>Taux suivi</th></tr></thead><tbody>{m.organisations.map(o=><tr key={o.organization_id??'plateforme'}><td>{o.nom??'Plateforme Gerimmo'}</td><td className="text-center">{o.automatiques}</td><td className="text-center">{o.humaines}</td><td className="text-center">{o.messages}</td><td className="text-center">{taux(o)}</td></tr>)}</tbody></table>{m.organisations.length===0&&<p className="py-3 text-sm text-muted-foreground">Aucune action mesurée pendant cette période.</p>}</div>}
 </section>;
}
