'use client';
import {useActionState,useState} from 'react';
import {enregistrerEtude} from '@/app/actions/etudes-territoriales';
import {DEPARTEMENTS} from '@/lib/territoire';
import {BoutonEnvoi} from '@/components/ui/bouton-envoi';
export function FormulaireEtude(){
 const [type,setType]=useState('concurrence');const [etat,action]=useActionState(enregistrerEtude,{});
 const champ='mt-1 w-full rounded-lg border border-[var(--filet)] bg-[var(--ivoire)] p-2.5';
 return <details className="section-ecran"><summary className="cursor-pointer text-lg font-semibold">Compléter une étude ou les résultats d’un essai local</summary><p className="mesure-lecture mt-3 text-sm text-muted-foreground">Les entreprises immobilières ne sont pas toutes des concurrentes. Consignez une étude datée des services comparables, ou un bilan de campagne dont les clients et les dépenses sont attribués au même département. Une donnée manquante reste inconnue.</p><form action={action} className="mt-4 grid gap-4 sm:grid-cols-2"><label>Département<select aria-label="Département" name="departement" required className={champ}><option value="">Choisir</option>{DEPARTEMENTS.map(d=><option key={d.code} value={d.code}>{d.code} · {d.nom}</option>)}</select></label><label>Information à compléter<select aria-label="Information à compléter" name="indicateur" value={type} onChange={e=>setType(e.target.value)} className={champ}><option value="concurrence">Concurrents directs recensés</option><option value="acquisition">Coût d’acquisition des clients</option></select></label><label>{type==='concurrence'?'Nombre de concurrents identifiés':'Nombre de clients réellement gagnés'}<input name="nombre" type="number" min={type==='concurrence'?0:1} max={type==='concurrence'?9999:999999} step="1" required className={champ}/></label>{type==='acquisition'&&<label>Dépense totale attribuée au département (€)<input name="depense" type="number" min="0" max="999999.99" step="0.01" required className={champ}/></label>}<label>Début de la période<input name="debut" type="date" required className={champ}/></label><label>Fin de la période<input name="fin" type="date" required className={champ}/></label><label className="sm:col-span-2">Source vérifiable : rapport ou références consultées<input name="source" required minLength={10} maxLength={1000} className={champ}/></label><label className="sm:col-span-2">Méthode et limites de l’étude<textarea name="methode" required minLength={20} maxLength={3000} className={champ} placeholder="Quels services avez-vous comparés ? Comment avez-vous attribué les clients et les dépenses à ce département ?"/></label><p className="sm:col-span-2 text-sm">Cette saisie conserve un résultat d’étude. Elle ne lance aucune publicité ni dépense.</p>{etat.erreur&&<p role="alert" className="err sm:col-span-2">{etat.erreur}</p>}{etat.succes&&<p role="status" className="sm:col-span-2">{etat.succes}</p>}<BoutonEnvoi>Enregistrer l’étude</BoutonEnvoi></form></details>;
}
