import Link from 'next/link';
import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {PUBLICS_VEILLE,sourceVeille} from '@/lib/veille-reglementaire';
export const metadata={title:'Les règles à connaître — Gerimmo'};
export default async function Page({searchParams}:{searchParams:Promise<{public?:string;page?:string;retour?:string}>}){
 const db=await createClient();const {data:{user}}=await db.auth.getUser();if(!user)redirect('/connexion?suite=%2Fveille');
 const p=await searchParams,publicChoisi=Object.hasOwn(PUBLICS_VEILLE,p.public??'')?p.public!:null,page=Math.max(1,Math.min(1000,Number.parseInt(p.page??'1')||1));
 const retour=p.retour&&/^\/(?:agence\/[0-9a-f-]{36}|locataire\/[0-9a-f-]{36}|artisan(?:\/entreprise)?)$/.test(p.retour)?p.retour:'/espaces';
 const filtre=(publicCible:string,pageCible=1)=>`/veille?${new URLSearchParams({public:publicCible,page:String(pageCible),retour})}`;
 let q=db.from('regulatory_watch_published').select('id,titre,resume,action_conseillee,publics,source_nom,source_url,application_le,valide_le',{count:'exact'}).order('valide_le',{ascending:false}).order('id').range((page-1)*20,page*20-1);if(publicChoisi)q=q.contains('publics',[publicChoisi]);const {data,error,count}=await q;
 return <main className="mx-auto max-w-5xl space-y-5 p-4 sm:p-7"><Link className="lien-discret" href={retour}>← Revenir à mon espace</Link><header className="rounded-2xl bg-cover bg-center p-6 text-white" style={{backgroundImage:"linear-gradient(100deg,rgba(13,35,85,.97),rgba(28,75,200,.78)),url('/illustrations/interieur-gerimmo-2026.jpg')"}}><h1 style={{color:'white'}} className="text-3xl font-semibold">Les règles à connaître</h1><p className="mt-3">Ce qui change pour votre activité ou votre location, et les démarches à prévoir.</p></header><nav className="flex flex-wrap gap-2" aria-label="Informations par public"><Link href={filtre('')} className={`filtre${!publicChoisi?' actif':''}`}>Tout voir</Link>{Object.entries(PUBLICS_VEILLE).map(([k,v])=><Link key={k} href={filtre(k)} className={`filtre${publicChoisi===k?' actif':''}`}>{v}</Link>)}</nav>{error?<p role="alert" className="err">Les informations sont momentanément indisponibles.</p>:data?.map(i=><article key={i.id} className="section-ecran"><div className="flex flex-wrap gap-2">{i.publics.map((x:string)=><span key={x} className="puce puce-prep">{PUBLICS_VEILLE[x as keyof typeof PUBLICS_VEILLE]}</span>)}</div><h2 className="mt-3 text-xl font-semibold">{i.titre}</h2><p className="mt-3 whitespace-pre-line">{i.resume}</p><div className="mt-4 rounded-xl bg-blue-50 p-4"><h3 className="font-semibold">Ce que vous pouvez prévoir</h3><p className="mt-2 whitespace-pre-line">{i.action_conseillee}</p></div><p className="mt-3 text-sm">{i.application_le?`Application annoncée : ${new Date(i.application_le+'T12:00:00Z').toLocaleDateString('fr-FR')}.`:'Date d’application à vérifier dans la source selon votre situation.'}</p>{sourceVeille(i.source_url)&&<a className="mt-3 inline-block underline" href={sourceVeille(i.source_url)!} target="_blank" rel="noreferrer">Consulter {i.source_nom}</a>}<p className="mt-2 text-xs text-muted-foreground">Information relue le {new Date(i.valide_le).toLocaleDateString('fr-FR')}. Vérifiez les conditions et les règles locales dans la source avant d’agir.</p></article>)}{!error&&!data?.length&&<p className="section-ecran">Aucune nouvelle information validée pour ce public. Vos alertes de dossier restent disponibles dans votre espace.</p>}<nav aria-label="Pagination" className="flex justify-between">{page>1?<Link href={filtre(publicChoisi??'',page-1)}>Précédente</Link>:<span/>}{page*20<(count??0)&&<Link href={filtre(publicChoisi??'',page+1)}>Suivante</Link>}</nav><p className="text-sm text-muted-foreground">Cette sélection aide à repérer les changements. Elle ne remplace pas l’examen de votre situation par un professionnel compétent.</p></main>;
}
