/** Correspondance d'affichage des mentions du PDF avec les champs existants.
 * Les règles et la liste des manquants restent celles du générateur de bail. */
const correspondances: [RegExp, string[]][] = [
  [/^date prévue de conclusion/i, ['bail.date_conclusion_prevue']],
  [/^Date d’entrée|^jj\/mm\/aaaa$/i, ['bail.date_debut']],
  [/^jour du mois$|jour d[’']échéance/i, ['bail.jour_echeance']],
  [/^montant mensuel$|^loyer \+ charges/i, ['bail.loyer_hc', 'bail.charges']],
  [/montant convenu/i, ['bail.depot_garantie']],
  [/provisions avec régularisation/i, ['bail.charges_mode']],
  [/^ex\. 2e trimestre/i, ['bail.irl_trimestre']],
  [/valeur de l'indice/i, ['bail.irl_valeur']],
  [/libre, plafonnement/i, ['bail.fixation_loyer']],
  [/domicile du bailleur, virement/i, ['bail.lieu_paiement']],
  [/^à échoir ou échu$/i, ['bail.paiement_echeance']],
  [/situation de la précédente location/i, ['bail.precedente_location']],
  [/^dernier loyer si/i, ['bail.dernier_loyer']],
  [/date du dernier versement/i, ['bail.dernier_loyer_versement']],
  [/révision du précédent loyer/i, ['bail.precedent_loyer_revise']],
  [/date de dernière révision/i, ['bail.dernier_loyer_revision']],
  [/^application des loyers de référence/i, ['bail.encadrement_loyer']],
  [/^loyer de référence €\/m²$/i, ['bail.loyer_reference']],
  [/^loyer de référence majoré/i, ['bail.loyer_reference_majore']],
  [/^complément de loyer$/i, ['bail.complement_loyer']],
  [/justification du complément/i, ['bail.complement_justification']],
  [/^existence de la servitude/i, ['bail.servitude_residence_principale']],
  [/événement précis justifiant/i, ['bail.duree_reduite_evenement']],
  [/^montant$/i, ['bail.travaux_recents_montant']],
  [/dépenses annuelles minimales/i, ['bail.dpe_depenses_min']],
  [/dépenses annuelles maximales/i, ['bail.dpe_depenses_max']],
  [/année\(s\) des prix de l’énergie/i, ['bail.dpe_annees_reference']],
  [/honoraires visite, dossier et bail — bailleur/i, ['bail.honoraires_bailleur']],
  [/honoraires visite, dossier et bail — locataire/i, ['bail.honoraires_locataire']],
  [/honoraires état des lieux — bailleur/i, ['bail.honoraires_edl_bailleur']],
  [/honoraires état des lieux — locataire/i, ['bail.honoraires_edl_locataire']],
  [/plafond de location selon/i, ['bail.zone_honoraires', 'bail.date_conclusion_prevue']],
  [/plafond état des lieux selon/i, ['bail.date_conclusion_prevue']],
  [/^le cas échéant$/i, ['lot.identifiant_fiscal']],
  [/^en m²$/i, ['lot.surface_m2']],
  [/^nombre$/i, ['lot.pieces']],
  [/^individuel ou collectif, énergie$/i, ['lot.chauffage', 'lot.eau_chaude']],
  [/^cave, grenier/i, ['lot.description']],
  [/^cave, parking/i, ['lot.locaux_privatifs']],
  [/^cuisine équipée/i, ['lot.equipements']],
  [/^avant 1949/i, ['bien.annee_construction']],
  [/^hall, ascenseur/i, ['bien.parties_communes']],
  [/^fibre, câble/i, ['bien.acces_tic']],
  [/^adresse complète/i, ['bien.address_line1', 'bien.postal_code', 'bien.city']],
  [/^classe DPE/i, ['diagnostic.classe_dpe']],
  [/^inventaire du mobilier/i, ['inventaire']],
  [/^surface privative$/i, ['chambre.surface_m2']],
  [/^volume privatif$/i, ['chambre.volume_m3']],
  [/^description de la chambre$/i, ['chambre.description']],
  [/^désignation de la chambre|^chambre privative/i, ['chambre.nom']],
  [/^chambre et équipements privatifs/i, ['chambre.nom', 'chambre.equipements']],
  [/^équipements privatifs/i, ['chambre.equipements']],
  [/^espaces partagés/i, ['chambre.espaces_partages']],
  [/^loyer maximum du logement/i, ['chambre.plafond']],
  [/^personne physique,/i, ['proprietaire.qualite']],
  [/^domicile ou siège social$/i, ['proprietaire.address_line1', 'proprietaire.postal_code', 'proprietaire.city']],
  [/^adresse actuelle$/i, ['locataire.address_line1', 'locataire.postal_code', 'locataire.city']],
  [/^Date de naissance du locataire$/i, ['locataire.date_naissance']],
  [/^commune de naissance$/i, ['locataire.commune_naissance']],
  [/^adresse électronique$/i, ['proprietaire.email', 'locataire.email']],
  [/^nom et prénom\(s\), ou dénomination$/i, ['proprietaire.nom', 'proprietaire.prenom']],
  [/^nom et prénom\(s\)$|^nom et prénom\(s\) du ou des locataires$|^nom du colocataire/i, ['locataire.nom', 'locataire.prenom']],
  [/^commune$|^adresse du mandataire$|carte et CCI|garantie financière|siret/i, ['profil']],
];
export function champsManquantsBail(mentions: string[]): Set<string> {
  return new Set(mentions.flatMap(mention => correspondances.filter(([motif]) => motif.test(mention)).flatMap(([, champs]) => champs)));
}
export function champBailManquant(mentions: string[], champ: string | string[], renseigne = false): boolean {
  if (renseigne) return false;
  const champs = champsManquantsBail(mentions);
  return (Array.isArray(champ) ? champ : [champ]).some(c => champs.has(c));
}
