import { createClient } from "@/lib/supabase/server";
import { premier } from "@/lib/postgrest";
import { eur,formaterDate } from "@/lib/ged";
import { TYPES_BAIL } from "@/lib/baux";
import { nomComplet } from "@/lib/roles-personnes";
import type { ValeursParcoursBail } from "@/lib/champs-etape-bail";
import type { ReactNode } from "react";
export async function RecapitulatifParcoursBail({orgId,lotId,bail,personnes,documents,signature}:{orgId:string;lotId:string;bail:ValeursParcoursBail;personnes:{nom:string;role:string}[];documents:ReactNode;signature:ReactNode}){
 const db=await createClient();
 const [logement,detentions]=await Promise.all([
  db.from("lots").select("*,bien:biens!lots_bien_id_fkey(*)").eq("id",lotId).eq("organization_id",orgId).maybeSingle(),
  db.from("detentions").select("quote_part,person:persons!detentions_person_id_fkey(nom,prenom)").eq("lot_id",lotId).eq("organization_id",orgId).is("date_fin",null),
 ]);
 const lot=logement.data,bien=premier(lot?.bien??null);
 const valeur=(v:unknown)=>v==null||v===""?"À compléter":String(v);
 const montant=(v:unknown)=>v==null?"À compléter":eur(Number(v));
 const sections:{titre:string;etape:number;lignes:[string,string][]}[]=[
  {titre:"Le bail",etape:1,lignes:[["Type",bail.chambre_id?"Colocation · contrat individuel":TYPES_BAIL[String(bail.type)]??valeur(bail.type)],["Date d’entrée",formaterDate(bail.date_debut as string|null)],["Conclusion prévue",formaterDate(bail.date_conclusion_prevue as string|null)],...(bail.meuble_etudiant?[["Bail étudiant","Oui · 9 mois"] as [string,string]]:[])]},
  {titre:"Les personnes",etape:2,lignes:[...(detentions.data??[]).map(d=>["Propriétaire",`${nomComplet(premier(d.person)??{nom:"À compléter",prenom:null})} · ${d.quote_part} %`] as [string,string]),...personnes.map(p=>[p.role,p.nom] as [string,string])]},
  {titre:"Le logement",etape:3,lignes:[["Lot",valeur(lot?.nom)],["Adresse",[bien?.address_line1,bien?.address_line2,bien?.postal_code,bien?.city].filter(Boolean).join(" · ")||"À compléter"],["Surface",`${valeur(lot?.surface_m2)} m² · ${valeur(lot?.pieces)} pièce(s)`],["Étage",lot?.etage??"Non précisé"],["Surface Carrez",lot?.surface_carrez?`${lot.surface_carrez} m²`:"Non renseignée (facultatif)"],["Identifiant fiscal",valeur(lot?.identifiant_fiscal)],["Chauffage",valeur(lot?.chauffage)],["Eau chaude",valeur(lot?.eau_chaude)],["Locaux privatifs",valeur(lot?.locaux_privatifs)],["Autres parties",valeur(lot?.description)],["Meublé",lot?.meuble?"Oui":"Non"],["Copropriété",bien?.copropriete===true?`Oui · tantièmes : ${lot?.tantieme??"non précisés"}`:bien?.copropriete===false?"Non":"À confirmer"]]},
  {titre:"Le loyer",etape:4,lignes:[["Loyer hors charges",montant(bail.loyer_hc)],["Charges",montant(bail.charges)],["Total mensuel",bail.loyer_hc!=null&&bail.charges!=null?eur(Number(bail.loyer_hc)+Number(bail.charges)):"À compléter"],["Dépôt de garantie",montant(bail.depot_garantie)],["Mode de charges",bail.charges_mode==="forfait"?"Forfait":"Provision avec régularisation"],["Révision annuelle",bail.revision_irl?`${valeur(bail.irl_trimestre)} · indice ${valeur(bail.irl_valeur)}`:"Non"],["Jour d’échéance",bail.jour_echeance == null ? "À compléter" : `Le ${bail.jour_echeance} de chaque mois`],["Paiement",bail.paiement_echeance==="echu"?"À terme échu":"À échoir"],["Lieu de paiement",valeur(bail.lieu_paiement)],["Précédente location",({premiere:"Première location",ancienne:"Départ depuis au moins 18 mois",recente:"Départ depuis moins de 18 mois"})[String(bail.precedente_location) as "premiere"]??"À confirmer"],...(bail.precedente_location==="recente"?[["Précédent loyer",montant(bail.dernier_loyer)] as [string,string]]:[])]},
  {titre:"Autres et clauses",etape:6,lignes:[["Encadrement par arrêté",bail.encadrement_loyer===true?`Oui · référence ${montant(bail.loyer_reference)}/m² · majoré ${montant(bail.loyer_reference_majore)}/m²`:bail.encadrement_loyer===false?"Non":"À confirmer"],["Servitude de résidence principale",bail.servitude_residence_principale===true?"Oui":bail.servitude_residence_principale===false?"Non":"À confirmer"],["Résiliation pour défaut d’assurance",bail.clause_resolutoire_assurance?"Prévue":"Non prévue"],["Résiliation pour troubles jugés",bail.clause_resolutoire_troubles?"Prévue":"Non prévue"],["Résiliation pour non-respect de la servitude",bail.clause_resolutoire_servitude?"Prévue":"Non prévue"],["Durée réduite",String(bail.duree_reduite_evenement||"Aucune")],["Travaux récents",String(bail.travaux_recents||"Aucun renseigné")],["Montant des travaux",bail.travaux_recents_montant==null?"Non renseigné":montant(bail.travaux_recents_montant)],["Travaux du locataire",String(bail.travaux_locataire||"Aucun renseigné")],["Clauses particulières",String(bail.clauses_particulieres||"Aucune")]]},
 ];
 return <div className="space-y-5"><p className="text-sm text-muted-foreground">Ce récapitulatif reprend vos informations enregistrées. Relisez chaque rubrique avant de créer les documents.</p>{(logement.error||detentions.error)&&<p role="alert">Une partie du dossier n’a pas pu être chargée. Rechargez avant de finaliser.</p>}<div className="bail-recap-grille">{sections.map(s=><section className="bail-recap-carte" key={s.titre}><header><h3>{s.titre}</h3><a href={`#etape-bail-${s.etape}`} className="lien-discret">Modifier</a></header><dl>{s.lignes.map(([k,v],i)=><div key={`${k}-${i}`}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>)}</div>{documents}{signature}</div>;
}
