import Link from 'next/link';
import {SuiviCorrection} from './suivi-correction';
import { createClient } from '@/lib/supabase/server';
import { MesureAutonomie } from '@/components/mesure-autonomie';
import { ETATS_DEVELOPPEMENT, ETATS_DOSSIER, TYPES_DOSSIER, lienDossier } from '@/lib/pilotage';
import { ActualiserDossiers, DecisionAmelioration, FormulaireDelegation, RevoquerDelegation } from './formulaire-delegation';
export const metadata={title:'Pilotage autonome — Gerimmo'};
const carte='rounded-2xl border border-border bg-white p-5 shadow-sm';
const filtres:Record<string,string>={tous:'Tous les dossiers',bail:'Locations',loyer:'Loyers en retard',incident:'Incidents',intervention:'Interventions',document:'Documents',rapport:'Finance et rapports'};
const risques:Record<string,string>={faible:'Impact limité',moyen:'À examiner',eleve:'Impact important',critique:'Priorité critique'};
export default async function PageAutonomie({searchParams}:{searchParams:Promise<{equipe?:string;page?:string}>}) {
 const p=await searchParams;const equipe=p.equipe&&Object.hasOwn(filtres,p.equipe)?p.equipe:'tous';
 const page=Math.max(1,Math.min(10000,Number.parseInt(p.page??'1',10)||1));
 const db=await createClient();
 let q=db.from('orchestration_cases').select('id,organization_id,dossier_type,dossier_id,prochaine_action,mode,etat,priorite,exception_message,updated_at,lien_action,agir_apres',{count:'exact'}).neq('etat','termine').order('rang_priorite').order('updated_at').order('id').range((page-1)*25,page*25-1);
 if(equipe!=='tous')q=q.eq('dossier_type',equipe);
 const [dossiers,propositions,delegations,orgs,comptes,regles,presence]=await Promise.all([
  q,db.from('development_proposals').select('id,titre,probleme,solution_proposee,risque,statut,revision,updated_at,rapport_controles,autorisee_le').order('updated_at',{ascending:false}).limit(30),
  db.from('supervision_delegations').select('id,account_id,termine_le,motif,active,revoquee_le').order('termine_le',{ascending:false}).limit(30),
  db.from('organizations').select('id,name'),db.from('accounts').select('id,email'),
  db.from('continuity_rules').select('cle,libelle,decision,delai_heures,active'),
  db.from('supervision_presence').select('derniere_presence').order('derniere_presence',{ascending:false}).limit(1),
 ]);
 const ids=(dossiers.data??[]).map(d=>d.id);
 const historique=ids.length?await db.from('orchestration_history').select('id,case_id,action,etat,created_at').in('case_id',ids).order('created_at',{ascending:false}).limit(200):{data:[],error:null};
 const noms=new Map((orgs.data??[]).map(o=>[o.id,o.name]));const emails=new Map((comptes.data??[]).map(c=>[c.id,c.email]));
 const maintenant=new Date();
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-7">
  {/* L'en-tête commun de la console (24/09) : le bandeau dégradé « Vos
      équipes Gerimmo » disparaît, et le titre reprend enfin le nom de
      l'entrée de barre. L'actualisation, geste principal, monte ici. */}
  <div className="entete-page"><div className="min-w-0 flex-[1_1_20rem]"><h1>Pilotage autonome</h1><p className="mt-2 max-w-3xl text-sm text-[var(--texte-secondaire)]">Le travail en cours et les décisions à prendre : la prochaine étape de chaque dossier, les améliorations préparées et le relais prévu en votre absence.</p></div><div className="flex flex-wrap items-center gap-3"><span className="mono-discret">Actualisé chaque matin</span><ActualiserDossiers /></div></div>
  {/* Les ancres portent le nom des sections visées ; « Marketing » et
      « Territoires » doublaient la barre sous d'autres noms (24/09). */}
  <Link href="/admin/equipes" className="btn-secondaire">Commander les équipes</Link>
  <nav aria-label="Sections du pilotage" className="flex flex-wrap items-center gap-x-4 gap-y-1 text-sm"><span className="text-[var(--texte-secondaire)]">Sur cette page :</span><a href="#dossiers" className="lien-discret text-sm">Prochaines étapes</a><a href="#mesures" className="lien-discret text-sm">Résultats</a><a href="#ameliorations" className="lien-discret text-sm">Améliorations</a><a href="#continuite" className="lien-discret text-sm">Pendant votre absence</a></nav>
  <section id="dossiers" className={carte}><div><h2 className="text-xl font-semibold">Les prochaines étapes</h2><p className="mt-1 text-sm text-muted-foreground">Les envois autorisés continuent selon les réglages de chaque organisation.</p></div>
  {/* Un clic par vue (24/09) : cinq pastilles au lieu d'une liste et d'un
      bouton « Afficher », et le filtre actif se voit. */}
  <nav aria-label="Filtrer par équipe" className="my-4 flex flex-wrap gap-2">{Object.entries(filtres).map(([k,v])=><Link key={k} href={k==='tous'?'/admin/autonomie':`/admin/autonomie?equipe=${k}`} scroll={false} aria-current={equipe===k?'true':undefined} className={`filtre${equipe===k?' actif':''}`}>{v}</Link>)}</nav>
  {/* Toute la carte est le lien (24/09) : seul « Ouvrir le dossier pour
      agir » réagissait au clic. */}
  {dossiers.error?<p role="alert" className="err">Le suivi des dossiers est indisponible. Actualisez avant de prendre une décision.</p>:<div className="space-y-3">{dossiers.data?.map(d=><Link key={d.id} href={lienDossier(d)} className={`group block rounded-xl border p-4 transition-colors hover:border-[var(--marque)] ${d.priorite==='urgente'?'border-amber-300 bg-amber-50':'border-border bg-muted/30 hover:bg-[var(--survol)]'}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-muted-foreground">{noms.get(d.organization_id)??'Organisation'} · {TYPES_DOSSIER[d.dossier_type]??'Dossier'}</p><h3 className="mt-1 font-semibold">{d.prochaine_action}</h3></div><span className="puce puce-prep">{ETATS_DOSSIER[d.etat]??'À vérifier'}</span></div>{d.agir_apres&&<p className="mt-2 text-xs text-muted-foreground">Échéance enregistrée : {new Date(d.agir_apres).toLocaleDateString('fr-FR',{timeZone:'Europe/Paris'})}</p>}{d.exception_message&&<p className="mt-2 text-sm text-amber-900">{d.exception_message}</p>}<span className="mt-3 flex justify-end"><span className="lien-discret text-[12.5px] group-hover:underline">Ouvrir le dossier →</span></span></Link>)}{!dossiers.data?.length&&<p className="text-sm text-muted-foreground">Aucun dossier à afficher pour ce filtre. Le bouton d’actualisation vérifie les dossiers existants.</p>}</div>}
  <details className="mt-4 border-t pt-3"><summary className="cursor-pointer font-medium">Dernières étapes des dossiers affichés</summary>{historique.error?<p role="alert" className="err">L’historique est momentanément indisponible.</p>:<ol className="mt-3 space-y-2">{historique.data?.slice(0,30).map(h=><li key={h.id} className="rounded-lg bg-muted/30 p-3 text-sm"><span className="text-xs text-muted-foreground">{new Date(h.created_at).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</span><p>{h.action}</p></li>)}{!historique.data?.length&&<li>Aucun changement enregistré depuis la mise en place de cet historique.</li>}</ol>}</details>
  <nav aria-label="Pages de dossiers" className="mt-4 flex justify-between text-sm">{page>1?<Link href={`?equipe=${equipe}&page=${page-1}`}>Précédente</Link>:<span/>}<span>{dossiers.count??'—'} dossiers · page {page}</span>{page*25<(dossiers.count??0)&&<Link href={`?equipe=${equipe}&page=${page+1}`}>Suivante</Link>}</nav></section>
  <div id="mesures"><MesureAutonomie detail titre="Ce que Gerimmo automatise, toutes organisations" /></div>
  <section id="ameliorations" className={carte}><h2 className="text-xl font-semibold">Agent qualité et améliorations</h2><p className="mt-2 text-sm text-muted-foreground">Les problèmes et idées transmis par les utilisateurs alimentent cette file. Chaque changement suit une préparation, des contrôles, une démonstration et une publication. L’accord porte sur une version précise et devient caduc si elle change.</p>
  {propositions.error?<p role="alert" className="err mt-3">Les améliorations sont momentanément indisponibles.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{propositions.data?.map(a=><article key={a.id} className="rounded-xl border bg-muted/30 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{a.titre}</h3><span className="puce puce-prep">{ETATS_DEVELOPPEMENT[a.statut]??'À examiner'}</span></div><p className="mt-2 text-xs text-muted-foreground">{risques[a.risque]??'Impact à vérifier'}</p><p className="mt-2 text-sm">{a.solution_proposee||a.probleme}</p><SuiviCorrection id={a.id} rapport={a.rapport_controles} statut={a.statut} autoriseeLe={a.autorisee_le} demande={[a.probleme,a.solution_proposee].filter(Boolean).join('\n\n')}/>{a.statut==='autorisation'&&a.revision&&<div className="mt-3"><DecisionAmelioration id={a.id} revision={a.revision}/></div>}</article>)}{!propositions.data?.length&&<p className="text-sm text-muted-foreground">Aucune proposition en attente.</p>}</div>}<Link href="/admin/retours" className="lien-discret mt-4 inline-block text-[12.5px]">Voir les retours →</Link></section>
  <section id="continuite" className={carte}><h2 className="text-xl font-semibold">Gerimmo pendant votre absence</h2><p className="mt-2 text-sm text-muted-foreground">Les envois et traitements déjà autorisés continuent. Les évolutions du logiciel attendent votre retour.</p><p className="mt-2 text-xs text-muted-foreground">{presence.error?'Dernière présence indisponible.':presence.data?.[0]?`Dernière présence de supervision : ${new Date(presence.data[0].derniere_presence).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}.`:'Aucune présence enregistrée.'}</p>
  <div className="mt-4 grid gap-5 lg:grid-cols-2"><div><h3 className="mb-3 font-semibold">Préparer un relais</h3><FormulaireDelegation /></div><div><h3 className="mb-3 font-semibold">Accès de remplacement</h3>{delegations.error?<p role="alert" className="err">Les accès ne peuvent pas être vérifiés actuellement.</p>:delegations.data?.map(d=>{const actif=d.active&&!d.revoquee_le&&new Date(d.termine_le)>maintenant;return <div key={d.id} className="mb-3 rounded-xl border p-3"><b className="break-all text-sm">{emails.get(d.account_id)??'Compte de remplacement'}</b><p className="mt-1 text-xs text-muted-foreground">{actif?'Actif jusqu’au':'Terminé le'} {new Date(d.termine_le).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</p><p className="my-2 text-sm">{d.motif}</p>{actif&&<RevoquerDelegation id={d.id}/>}</div>})}{!delegations.error&&!delegations.data?.length&&<p className="text-sm text-muted-foreground">Aucun relais désigné. Choisissez une personne de confiance avant une longue absence.</p>}<p className="mt-3 text-xs text-muted-foreground">Le remplaçant retrouve le suivi sur la page « Mes espaces » après connexion et double vérification.</p></div></div>
  <details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-semibold">Ce qui peut continuer seul</summary>{regles.error?<p className="err">Règles indisponibles.</p>:<ul className="mt-3 space-y-2">{regles.data?.map(r=><li key={r.cle} className="rounded-lg bg-muted/40 p-3 text-sm"><b>{r.libelle}</b><span className="mt-1 block text-muted-foreground">{r.decision==='agir_seul'?'Traitement prévu dans les autorisations existantes':r.decision==='delegue_requis'?'Un responsable autorisé doit décider':'La décision attend votre retour'}. La règle ne crée pas un droit supplémentaire.</span></li>)}</ul>}</details></section>
 </main>;
}
