import Link from 'next/link';
import { createClient } from '@/lib/supabase/server';
import { MesureAutonomie } from '@/components/mesure-autonomie';
import { ETATS_DEVELOPPEMENT, ETATS_DOSSIER, TYPES_DOSSIER, lienDossier } from '@/lib/pilotage';
import { ActualiserDossiers, DecisionAmelioration, FormulaireDelegation, RevoquerDelegation } from './formulaire-delegation';
export const metadata={title:'Pilotage autonome — Gerimmo'};
const carte='rounded-2xl border border-border bg-white p-5 shadow-sm';
const filtres:Record<string,string>={tous:'Tous les dossiers',bail:'Locations',incident:'Incidents et artisans',document:'Documents',rapport:'Finance et rapports'};
const risques:Record<string,string>={faible:'Impact limité',moyen:'À examiner',eleve:'Impact important',critique:'Priorité critique'};
export default async function PageAutonomie({searchParams}:{searchParams:Promise<{equipe?:string;page?:string}>}) {
 const p=await searchParams;const equipe=p.equipe&&Object.hasOwn(filtres,p.equipe)?p.equipe:'tous';
 const page=Math.max(1,Math.min(10000,Number.parseInt(p.page??'1',10)||1));
 const db=await createClient();
 let q=db.from('orchestration_cases').select('id,organization_id,dossier_type,dossier_id,prochaine_action,mode,etat,priorite,exception_message,updated_at,lien_action',{count:'exact'}).neq('etat','termine').order('priorite',{ascending:false}).order('updated_at',{ascending:false}).range((page-1)*25,page*25-1);
 if(equipe!=='tous')q=q.eq('dossier_type',equipe);
 const [dossiers,propositions,delegations,orgs,comptes,regles,presence]=await Promise.all([
  q,db.from('development_proposals').select('id,titre,probleme,solution_proposee,risque,statut,revision,updated_at').order('updated_at',{ascending:false}).limit(30),
  db.from('supervision_delegations').select('id,account_id,termine_le,motif,active,revoquee_le').order('termine_le',{ascending:false}).limit(30),
  db.from('organizations').select('id,name'),db.from('accounts').select('id,email'),
  db.from('continuity_rules').select('cle,libelle,decision,delai_heures,active'),
  db.from('supervision_presence').select('derniere_presence').order('derniere_presence',{ascending:false}).limit(1),
 ]);
 const noms=new Map((orgs.data??[]).map(o=>[o.id,o.name]));const emails=new Map((comptes.data??[]).map(c=>[c.id,c.email]));
 const maintenant=new Date();
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-7">
  <header className="rounded-2xl bg-gradient-to-r from-[var(--encre)] to-[var(--marque)] p-6 text-white"><p className="text-xs uppercase tracking-widest text-white/75">Vos équipes Gerimmo</p><h1 className="mt-2 text-3xl font-semibold">Le travail en cours, les décisions à prendre</h1><p className="mt-3 max-w-3xl text-sm text-white/85">Retrouvez les prochaines étapes de chaque dossier, les améliorations préparées et le relais prévu en votre absence.</p></header>
  <nav aria-label="Sections du pilotage" className="flex flex-wrap gap-2"><a href="#dossiers" className="btn-secondaire">Dossiers</a><a href="#mesures" className="btn-secondaire">Résultats</a><a href="#ameliorations" className="btn-secondaire">Améliorations</a><a href="#continuite" className="btn-secondaire">Continuité</a><Link href="/admin/marketing" className="btn-secondaire">Marketing</Link><Link href="/admin/territoire" className="btn-secondaire">Territoires</Link></nav>
  <section id="dossiers" className={carte}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">Les prochaines étapes</h2><p className="mt-1 text-sm text-muted-foreground">Actualisation chaque matin. Les envois autorisés continuent selon les réglages de chaque organisation.</p></div><ActualiserDossiers /></div>
  <form className="my-4 flex items-end gap-3"><label className="text-sm">Équipe<select name="equipe" defaultValue={equipe} className="ml-2 rounded-lg border bg-white p-2">{Object.entries(filtres).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button type="submit" className="btn-secondaire">Afficher</button></form>
  {dossiers.error?<p role="alert" className="err">Le suivi des dossiers est indisponible. Actualisez avant de prendre une décision.</p>:<div className="space-y-3">{dossiers.data?.map(d=><article key={d.id} className={`rounded-xl border p-4 ${d.priorite==='urgente'?'border-amber-300 bg-amber-50':'border-border bg-muted/30'}`}><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-muted-foreground">{noms.get(d.organization_id)??'Organisation'} · {TYPES_DOSSIER[d.dossier_type]??'Dossier'}</p><h3 className="mt-1 font-semibold">{d.prochaine_action}</h3></div><span className="puce puce-prep">{ETATS_DOSSIER[d.etat]??'À vérifier'}</span></div>{d.exception_message&&<p className="mt-2 text-sm text-amber-900">{d.exception_message}</p>}<Link href={lienDossier(d)} className="mt-3 inline-block text-sm font-medium text-[var(--marque)] underline">Ouvrir le dossier pour agir</Link></article>)}{!dossiers.data?.length&&<p className="text-sm text-muted-foreground">Aucun dossier à afficher pour ce filtre. Le bouton d’actualisation vérifie les dossiers existants.</p>}</div>}
  <nav aria-label="Pages de dossiers" className="mt-4 flex justify-between text-sm">{page>1?<Link href={`?equipe=${equipe}&page=${page-1}`}>Précédente</Link>:<span/>}<span>{dossiers.count??'—'} dossiers · page {page}</span>{page*25<(dossiers.count??0)&&<Link href={`?equipe=${equipe}&page=${page+1}`}>Suivante</Link>}</nav></section>
  <div id="mesures"><MesureAutonomie detail /></div>
  <section id="ameliorations" className={carte}><h2 className="text-xl font-semibold">Agent qualité et améliorations</h2><p className="mt-2 text-sm text-muted-foreground">Les problèmes et idées transmis par les utilisateurs alimentent cette file. Chaque changement suit une préparation, des contrôles, une démonstration et une publication. L’accord porte sur une version précise et devient caduc si elle change.</p>
  {propositions.error?<p role="alert" className="err mt-3">Les améliorations sont momentanément indisponibles.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{propositions.data?.map(a=><article key={a.id} className="rounded-xl border bg-muted/30 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{a.titre}</h3><span className="puce puce-prep">{ETATS_DEVELOPPEMENT[a.statut]??'À examiner'}</span></div><p className="mt-2 text-xs text-muted-foreground">{risques[a.risque]??'Impact à vérifier'}</p><p className="mt-2 text-sm">{a.solution_proposee||a.probleme}</p>{a.statut==='autorisation'&&a.revision&&<div className="mt-3"><DecisionAmelioration id={a.id} revision={a.revision}/></div>}</article>)}{!propositions.data?.length&&<p className="text-sm text-muted-foreground">Aucune proposition en attente.</p>}</div>}<Link href="/admin/retours" className="mt-4 inline-block text-sm underline">Voir les retours et les réponses aux utilisateurs</Link></section>
  <section id="continuite" className={carte}><h2 className="text-xl font-semibold">Gerimmo pendant votre absence</h2><p className="mt-2 text-sm text-muted-foreground">Les envois et traitements déjà autorisés continuent sur le service hébergé. Le développement du code par cette session demande que son environnement d’exécution soit disponible.</p><p className="mt-2 text-xs text-muted-foreground">{presence.error?'Dernière présence indisponible.':presence.data?.[0]?`Dernière présence de supervision : ${new Date(presence.data[0].derniere_presence).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}.`:'Aucune présence enregistrée.'}</p>
  <div className="mt-4 grid gap-5 lg:grid-cols-2"><div><h3 className="mb-3 font-semibold">Préparer un relais</h3><FormulaireDelegation /></div><div><h3 className="mb-3 font-semibold">Accès de remplacement</h3>{delegations.error?<p role="alert" className="err">Les accès ne peuvent pas être vérifiés actuellement.</p>:delegations.data?.map(d=>{const actif=d.active&&!d.revoquee_le&&new Date(d.termine_le)>maintenant;return <div key={d.id} className="mb-3 rounded-xl border p-3"><b className="break-all text-sm">{emails.get(d.account_id)??'Compte de remplacement'}</b><p className="mt-1 text-xs text-muted-foreground">{actif?'Actif jusqu’au':'Terminé le'} {new Date(d.termine_le).toLocaleString('fr-FR',{timeZone:'Europe/Paris'})}</p><p className="my-2 text-sm">{d.motif}</p>{actif&&<RevoquerDelegation id={d.id}/>}</div>})}{!delegations.error&&!delegations.data?.length&&<p className="text-sm text-muted-foreground">Aucun relais désigné. Choisissez une personne de confiance avant une longue absence.</p>}<p className="mt-3 text-xs text-muted-foreground">Le remplaçant retrouve le suivi sur la page « Mes espaces » après connexion et double vérification.</p></div></div>
  <details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-semibold">Ce qui peut continuer seul</summary>{regles.error?<p className="err">Règles indisponibles.</p>:<ul className="mt-3 space-y-2">{regles.data?.map(r=><li key={r.cle} className="rounded-lg bg-muted/40 p-3 text-sm"><b>{r.libelle}</b><span className="mt-1 block text-muted-foreground">{r.decision==='agir_seul'?'Traitement prévu dans les autorisations existantes':r.decision==='delegue_requis'?'Un responsable autorisé doit décider':'La décision attend votre retour'}. La règle ne crée pas un droit supplémentaire.</span></li>)}</ul>}</details></section>
 </main>;
}
